# Score For Random Neural Network For results1 GeneExpression

In [17]:
import pandas as pd
import numpy as np

import torch

#imports necessary to define a neural network 
import torch.nn as nn
import torch.nn.functional as F

#ensure you are using GPU.
if torch.cuda.is_available():  
  dev = "cuda:0" 
else:  
  dev = "cpu"  

device = torch.device(dev)
print(device)

dtype = torch.cuda.FloatTensor

cuda:0


In [18]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split

trdt1=pd.read_csv('C:\\Users\\Ant Pc\\GitHub\\pROJ\\Genotype\\TrainingGenotype.csv')
trdt=pd.read_csv('C:\\Users\\Ant Pc\\GitHub\\pROJ\\Geneexpression0\\traingeneexpression.csv',header=None)
tstdt=pd.read_csv('C:\\Users\\Ant Pc\\GitHub\\pROJ\\Geneexpression0\\testgeneexpression.csv',header=None)

tstdt=np.array(tstdt)
tstdt=np.transpose(tstdt)
tstdt=pd.DataFrame(tstdt)

trdt=np.array(trdt)
trdt=np.transpose(trdt)
trdt=pd.DataFrame(trdt)

results1=trdt1['Phenotype1']
results2=trdt1['Phenotype2']

testfeatures=tstdt

#random input matrix
nsamples=3000
X=np.random.randn(nsamples,6)

In [19]:
randmatr=pd.read_csv('C:/Users/Ant Pc/GitHub/CSB-PROJ/Randmatr.csv', header=None).values
class Net1(nn.Module):

    def __init__(self):
        super(Net1, self).__init__()
        
        # an affine operation: y = Wx + b
        
        self.rand=nn.Linear(28395,1000).cuda()
        self.fc1=nn.Linear(1000,3200).cuda()
        self.fc6 = nn.Linear(3200,1).cuda()
        
        #set weights as random projection matrix
        self.rand.weight.data = torch.transpose(torch.from_numpy(randmatr),0,1).type(dtype)
        
    def forward(self, x):
        x = self.rand(x).cuda()
        x = F.relu(x).cuda()
        x = F.relu(self.fc1(x)).cuda()  
        x = self.fc6(x).cuda()
        
        return x

# Load
PATH="C:/Users/Ant Pc/GitHub/CSB-PROJ/finetunedrandproj223.pt"
model = Net1()
model.cuda()
model.load_state_dict(torch.load(PATH))
print(model)

Net1(
  (rand): Linear(in_features=28395, out_features=1000, bias=True)
  (fc1): Linear(in_features=1000, out_features=3200, bias=True)
  (fc6): Linear(in_features=3200, out_features=1, bias=True)
)


In [20]:
model(torch.from_numpy(tstdt.values).type(dtype))

tensor([[22.5182],
        [21.9931],
        [22.7467],
        [23.0400],
        [22.7265],
        [22.6154],
        [22.8180],
        [22.4691],
        [23.1365],
        [23.7675],
        [22.9942],
        [22.9694],
        [22.7283],
        [22.8931],
        [23.9798],
        [23.0947],
        [22.9032],
        [23.0008],
        [22.9759],
        [23.2112],
        [22.8622],
        [23.1588],
        [22.9898],
        [22.5035],
        [22.8490],
        [24.0814],
        [22.3548],
        [23.6831],
        [22.3105],
        [22.7259]], device='cuda:0', grad_fn=<AddmmBackward>)

In [21]:
#actual values
gold=pd.read_csv('C:\\Users\\Ant Pc\\GitHub\\pROJ\\Genotype\\gold.csv', sep='\t')
gold.drop(gold.columns[-1],axis=1,inplace=True)

import scipy.stats
import math

gold1=gold.iloc[1,:]
gold1=gold1.values
print(gold1)

[21.526  25.665  20.076  20.297  18.941  11.919  18.4135 19.06   18.812
 11.1865 20.435  11.601  18.7015 18.712  19.851  20.0065 21.0215 15.227
 18.8225 19.793  15.52   22.5095 15.5185 25.125  20.675  21.085  19.6515
 23.069  21.3445 21.8325]


In [22]:
dt1=np.transpose(gold1)
dt1=np.reshape(dt1,[30])
dt11=model(torch.from_numpy(tstdt.values).type(dtype)).cpu().detach().numpy()
dt11=dt11.astype('float')
dt1=dt1.astype('float')
dt11=np.reshape(dt11,[30])

score1=math.log(scipy.stats.pearsonr(dt1, dt11)[1])
print(scipy.stats.pearsonr(dt1, dt11))

(-0.20503403021662195, 0.27708207286156344)


In [23]:
print(-score1)

1.2834415247615791


C:/Users/Ant Pc/GitHub/CSB-PROJ/Randmatr1.csv
C:/Users/Ant Pc/GitHub/CSB-PROJ/finetunedrandproj2.pt

# Scores for Rest of ML algos along with Implementation

In [2]:
import pandas as pd
import numpy as np

trdt1=pd.read_csv('E:/Git/Computational-Systems-Biology-Project/DREAM5 SYSTEMS GENETICS CHALLENGE/PART B/TrainingGenotype.csv')
trdt=pd.read_csv('E:/Git/Computational-Systems-Biology-Project/DREAM5 SYSTEMS GENETICS CHALLENGE/PART B/DREAM5_SysGenB_TrainingData/DREAM5_SysGenB_TrainingExpressionData.csv')
tstdt=pd.read_csv('E:/Git/Computational-Systems-Biology-Project/DREAM5 SYSTEMS GENETICS CHALLENGE/PART B/DREAM5_SysGenB_TestData/DREAM5_SysGenB2_TestExpressionData.csv')

trdt.drop('A', axis=1, inplace=True)
trdt=np.array(trdt)
trdt=np.transpose(trdt)
trdt=pd.DataFrame(trdt)

tstdt.drop('A', axis=1, inplace=True)
tstdt=np.array(tstdt)
tstdt=np.transpose(tstdt)
tstdt=pd.DataFrame(tstdt)

features=trdt.copy()

testfeatures=tstdt.copy()

results1=trdt1['Phenotype1']
results2=trdt1['Phenotype2']

from sklearn import preprocessing
standard= preprocessing.StandardScaler()

features = standard.fit_transform(features)
testfeatures=standard.fit_transform(testfeatures)

features=pd.DataFrame(features)
testfeatures=pd.DataFrame(testfeatures)

In [5]:
#Linear Regression

from sklearn import linear_model
import math
from math import sqrt
from sklearn.metrics import mean_squared_error

lmr = linear_model.LinearRegression()
modellr = lmr.fit(features,results1)
        
predictions = modellr.predict(testfeatures)
pred=pd.DataFrame(predictions)
        
pred.to_csv('LinearRegressionPredictions1.csv')

lmr1 = linear_model.LinearRegression()
modellr1 = lmr1.fit(features,results2)
        
predictions1 = modellr1.predict(testfeatures)
pred1=pd.DataFrame(predictions1)
        
pred1.to_csv('LinearRegressionPredictions2.csv')
predic1=pd.read_csv('C:/Users/Ant Pc/GitHub/CSBFinal/LinearRegressionPredictions1.csv')
predic2=pd.read_csv('C:/Users/Ant Pc/GitHub/CSBFinal/LinearRegressionPredictions2.csv')


gold1=gold.iloc[0,:]
gold1=gold1.values

gold2=gold.iloc[1,:]
gold2=gold2.values

dt1=np.transpose(gold1)
dt11=predic1.iloc[:,1]

dt2=np.transpose(gold2)
dt22=predic2.iloc[:,1]

print(scipy.stats.pearsonr(dt2, dt22))
print(scipy.stats.pearsonr(dt1, dt11))
print('linear regression')
score=math.log(scipy.stats.pearsonr(dt1, dt11)[1])+math.log(scipy.stats.pearsonr(dt2, dt22)[1])
print(-score)

(-0.12892252913322905, 0.49715372195989077)
(-0.1345260809162228, 0.4784781147214621)
linear regression
1.4360008073850459


In [10]:
#Linear Regression

from sklearn import linear_model
import math
from math import sqrt
from sklearn.metrics import mean_squared_error

lmr = linear_model.Lasso(alpha=0.1)
modellr = lmr.fit(features,results1)
        
predictions = modellr.predict(testfeatures)
pred=pd.DataFrame(predictions)
        
pred.to_csv('LassoRegressionPredictions1.csv')

lmr1 = linear_model.Lasso(alpha=0.1)
modellr1 = lmr1.fit(features,results2)
        
predictions1 = modellr1.predict(testfeatures)
pred1=pd.DataFrame(predictions1)
        
pred1.to_csv('LassoRegressionPredictions2.csv')
predic1=pd.read_csv('C:/Users/Ant Pc/GitHub/CSBFinal/LassoRegressionPredictions1.csv')
predic2=pd.read_csv('C:/Users/Ant Pc/GitHub/CSBFinal/LassoRegressionPredictions2.csv')


gold1=gold.iloc[0,:]
gold1=gold1.values

gold2=gold.iloc[1,:]
gold2=gold2.values

dt1=np.transpose(gold1)
dt11=predic1.iloc[:,1]

dt2=np.transpose(gold2)
dt22=predic2.iloc[:,1]

print(scipy.stats.pearsonr(dt2, dt22))
print(scipy.stats.pearsonr(dt1, dt11))
print('lasso regression')
score=math.log(scipy.stats.pearsonr(dt1, dt11)[1])+math.log(scipy.stats.pearsonr(dt2, dt22)[1])
print(-score)

(-0.032320167563577314, 0.8653665567055462)
(0.0645359585556062, 0.7347516271148913)
lasso regression
0.4528248560063368


In [11]:
#Decision Tree Regressor
from sklearn.tree import DecisionTreeRegressor
import math
from math import sqrt
from sklearn.metrics import mean_squared_error

lmr = DecisionTreeRegressor(criterion='mse')
modellr = lmr.fit(features,results1)
        
predictions = modellr.predict(testfeatures)
pred=pd.DataFrame(predictions)
        
pred.to_csv('DecisionTreeRegressionPredictions1.csv')

lmr1 = DecisionTreeRegressor(criterion='mse')
modellr1 = lmr1.fit(features,results2)
        
predictions1 = modellr1.predict(testfeatures)
pred1=pd.DataFrame(predictions1)
        
pred1.to_csv('DecisionTreeRegressionPredictions2.csv')
predic1=pd.read_csv('C:/Users/Ant Pc/GitHub/CSBFinal/DecisionTreeRegressionPredictions1.csv')
predic2=pd.read_csv('C:/Users/Ant Pc/GitHub/CSBFinal/DecisionTreeRegressionPredictions2.csv')


gold1=gold.iloc[0,:]
gold1=gold1.values

gold2=gold.iloc[1,:]
gold2=gold2.values

dt1=np.transpose(gold1)
dt11=predic1.iloc[:,1]

dt2=np.transpose(gold2)
dt22=predic2.iloc[:,1]

print(scipy.stats.pearsonr(dt2, dt22))
print(scipy.stats.pearsonr(dt1, dt11))
print('DecisionTree regression')
score=math.log(scipy.stats.pearsonr(dt1, dt11)[1])+math.log(scipy.stats.pearsonr(dt2, dt22)[1])
print(-score)

(-0.24636018566764772, 0.18939563124699155)
(-0.3745316539741392, 0.041437609288491134)
DecisionTree regression
4.8474835383838375


In [6]:
#Random Forest Regressor
from sklearn.ensemble import RandomForestRegressor
import math
from math import sqrt
from sklearn.metrics import mean_squared_error

lmr = RandomForestRegressor(n_estimators = 100, random_state = 42)
modellr = lmr.fit(features,results1)
        
predictions = modellr.predict(testfeatures)
pred=pd.DataFrame(predictions)
        
pred.to_csv('RandomForestRegressionPredictions1.csv')

lmr1 =RandomForestRegressor(n_estimators = 100, random_state = 42)
modellr1 = lmr1.fit(features,results2)
        
predictions1 = modellr1.predict(testfeatures)
pred1=pd.DataFrame(predictions1)
        
pred1.to_csv('RandomForestRegressionPredictions2.csv')
predic1=pd.read_csv('C:/Users/Ant Pc/GitHub/CSBFinal/RandomForestRegressionPredictions1.csv')
predic2=pd.read_csv('C:/Users/Ant Pc/GitHub/CSBFinal/RandomForestRegressionPredictions2.csv')


gold1=gold.iloc[0,:]
gold1=gold1.values

gold2=gold.iloc[1,:]
gold2=gold2.values

dt1=np.transpose(gold1)
dt11=predic1.iloc[:,1]

dt2=np.transpose(gold2)
dt22=predic2.iloc[:,1]

print(scipy.stats.pearsonr(dt2, dt22))
print(scipy.stats.pearsonr(dt1, dt11))
print('RandomForest regression')
score=math.log(scipy.stats.pearsonr(dt1, dt11)[1])+math.log(scipy.stats.pearsonr(dt2, dt22)[1])
print(-score)

(-0.04909508315469259, 0.7966894843379564)
(-0.4840547151063198, 0.006721092879772)
RandomForest regression
5.229794788458052


In [14]:
p=pd.read_csv('C:/Users/Ant Pc/GitHub/CSB-Proj/1.csv', header=None)
print(p)
standard= preprocessing.StandardScaler()
p=standard.fit_transform(p.values.T)
print(p.T[1])
modellr1.predict(p)

              0
0      0.012051
1      1.419691
2      0.046810
3      0.416242
4      0.848606
...         ...
28390  1.235428
28391  1.092103
28392  1.141177
28393  0.815176
28394  0.122309

[28395 rows x 1 columns]
[0.]


array([20.421455])

In [24]:
modellr1.predict(tstdt)

array([20.128055, 20.128055, 20.128055, 20.128055, 20.128055, 20.128055,
       20.128055, 20.128055, 20.128055, 20.128055, 20.71477 , 20.128055,
       20.128055, 20.128055, 20.128055, 20.128055, 20.128055, 20.128055,
       20.128055, 20.128055, 20.128055, 20.128055, 20.128055, 20.1856  ,
       20.128055, 20.128055, 20.128055, 20.219745, 20.128055, 20.128055])

In [26]:
p=pd.read_csv('C:/Users/Ant Pc/GitHub/CSB-Proj/1.csv', header=None)
model(torch.from_numpy(p.values.T).type(dtype))

tensor([[-0.0252]], device='cuda:0', grad_fn=<AddmmBackward>)